config/routes.rb
Rails.application.routes.draw do

  root   "events#index"
  get    "/signup",   to: "users#new"
  post   "/signup",   to: "users#create" 
  get    "/login",    to: "sessions#new"
  post   "/login",    to: "sessions#create"
  delete "/logout",   to: "sessions#destroy"

  resources :users,   only: [:new, :create, :show, :index]
  resources :events,  only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    scope :previous, -> { where("date < ?", Time.now) }
    scope :upcoming, -> { where("date > ?", Time.now) }
    
    belongs_to  :creator, class_name: "User"
    has_many    :invitations, foreign_key: :attended_event_id
    has_many    :attendees, through: :invitations, source: :attendee
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
    # We want to access the token but not save it in the database (like the password with "has_secure_password")

    attr_accessor :remember_token 
    before_save { email.downcase! }
    validates :name,        presence: true, 
                            length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,       presence: true, 
                            length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: false }

    validates :password,    presence: true, 
                            length: { minimum: 6 }

    has_secure_password

    has_many :created_events, foreign_key: :creator_id, class_name: "Event"
    has_many :invitations, foreign_key: :attendee_id
    has_many :attended_events, through: :invitations




    # Returns hash digest/encryption of the given string
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token/string
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions
    def remember 
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest (similar to #authenticate method for passwords)
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(self.remember_digest).is_password?(remember_token)
    end

    def forget 
      update_attribute(:remember_digest, nil)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index 
        @events = Event.all
        @previous_events = Event.previous
        @upcoming_events = Event.upcoming
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)
        if @event.save 
            redirect_to current_user
        else 
            render "new"
        end
    end

    def show
        @event = Event.find(params[:id])
        @creator = User.find(@event.creator_id)
        @attendees = @event.attendees
    end

    private 

        def event_params
            params.require(:event).permit(:date, :location)
        end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    @invitation = Invitation.new 
    @invitation.attendee_id = current_user.id 
    @invitation.attended_event_id = params[:id]
    if @invitation.save 
      flash[:success] = "Yay, you will attend this event."
      redirect_to events_path
    else 
      flash[:danger] = "Sorry, but something went wrong."
      redirect_to events_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user
    else 
      flash.now[:danger] = "Invalid email/password combination" 
      render "new"
    end
  end 

  def destroy 
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @users = User.all
    end

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            log_in @user
            flash[:success] = "Welcome to the Events App!"
            redirect_to @user 
        else 
            render "new"
        end
    end

    def show
        @user = User.find(params[:id]) 
        @created_events = Event.all.where(creator_id: params[:id])
        @attended_events = @user.attended_events
        @upcoming_events = @attended_events.upcoming
        @previous_events = @attended_events.previous
    end

    private 
        def user_params 
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember 
        cookies.permanent.signed[:user_id] = user.id 
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id]) 
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id) 
            if user && user.authenticated?(cookies[:remember_token])
                login(user)
                @current_user = user 
            end
        end
    end

    def logged_in? 
        !current_user.nil?
    end

    def log_out 
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)
        user.forget 
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li>Location: <%= event.location %></li>
<li>Date: <%= event.date.strftime("%B %d, %Y - %k:%M") %></li>
<li><%= link_to "To the event", event_path(event) %></li>
<p></p>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<ul>
    <%= render partial: "event", collection: @upcoming_events, as: :event%>
</ul>

<h1>Previous Events</h1>

<ul>
    <%= render partial: "event", collection: @previous_events, as: :event%>
</ul>

app/views/events/new.html.erb
<h1>Add a new event</h1>

<%= form_for (@event) do |f| %>
    <p>
        <%= f.label :date %>
        <%= f.datetime_field :date %>
    </p>

    <p>
        <%= f.label :location %>
        <%= f.text_field :location %>
    </p>

    <%= f.submit %>

<% end %>

app/views/events/show.html.erb
<h1>Event: <%= @event.location %></h1>
<p>Creator: <%= @creator.name %></p>

<h2>All attendees</h2>

<ul>
<% @attendees.each do |attendant| %>
    <li><%= attendant.name %></li>
<% end %>
</ul>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Create Event", new_event_path %></li>
          <li><%= link_to "My Page", current_user %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>  
          <li>Logged in as <%= current_user.name %></li>        
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    The form contains <%= pluralize(@user.errors.count, "error") %>.

    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>
<ul>
<% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
    <li><%= user.email %></li>
    <p></p>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_for @user, url: signup_path do |f| %>

    <%= render "shared/error_messages" %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :email %>
        <%= f.email_field :email %> 
    </p>
    <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </p>
    <p>
        <%= f.submit "Create my account" %>
    </p>
<% end %> 

app/views/users/show.html.erb
<h1><%= @user.name %>'s Page</h1> 
<p>Email: <%= @user.email %></p>

<h1>Created Events</h1>

<ul>
    <%= render partial: "/events/event", collection: @created_events, as: :event %>
</ul>

<h1>Upcoming Attended Events</h1>
<ul>
    <%= render partial: "/events/event", collection: @upcoming_events, as: :event %>
</ul>

<h1>Previous Attended Events</h1>
<ul>
    <%= render partial: "/events/event", collection: @previous_events, as: :event %>
</ul>